[package]
name = "split_string"
version = "0.1.0"
edition = "2021"
authors = ["Khamdany"]
description = "Application to split string from file"
license = "GPL-2.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
